### ISSUE TITLE
Size of dataset and abbreviations

### ISSUE THREAD

**Issue by emilyemchen** [brainhack-school2020/lizizakson_commonalitiesAcrossDomains#1]
Really great idea here! I was wondering what size dataset you were planning to work with (i.e. how many participants). Additionally, would suggest spelling out what HCP stands for!

**Comment by lizizakson** [comment]
Thank you for the comment!
I think I'll start with a small sample (around 10 subjects), and then after I'll have an established pipeline, I'll add as much as I can (in the limits of time and resources that I have:)).
